[package]
name = "rest_api_client"
version = "0.1.0"
authors = ["Jérémy Thulliez <jeremy.thulliez@zenika.com>"]
edition = "2018"

[dependencies]
reqwest = "0.9.5"
serde = "1.0.82"
serde_derive = "1.0.82"
